// This file is generated by `provider-preset-gen`. Do not edit manually.
use std::borrow::Cow;

#[allow(unused_imports)]
use provider::{ModelCost, ModelInfo, ModelLimit};

use super::{OpenAiConfigPreset, REASONING_LMH};
use crate::config::OpenAiApiSurface;

pub const MODELS: &[ModelInfo] = &[
    ModelInfo {
        id: Cow::Borrowed("deepseek-chat"),
        name: Cow::Borrowed("DeepSeek Chat"),
        family: Some(Cow::Borrowed("deepseek")),
        reasoning_efforts: Cow::Borrowed(&[]),
        tool_call: true,
        attachment: true,
        structured_output: None,
        temperature: Some(true),
        knowledge: Some(Cow::Borrowed("2025-09")),
        release_date: Some(Cow::Borrowed("2025-12-01")),
        last_updated: Some(Cow::Borrowed("2026-02-28")),
        open_weights: Some(true),
        input_modalities: Cow::Borrowed(&["text"]),
        output_modalities: Cow::Borrowed(&["text"]),
        cost: Some(ModelCost { input: 0.28, output: 0.42, reasoning: None, cache_read: Some(0.028), cache_write: None, input_audio: None, output_audio: None }),
        limit: Some(ModelLimit { context: 128000, input: None, output: 8192 }),
        status: None,
        capabilities: None,
    },
    ModelInfo {
        id: Cow::Borrowed("deepseek-reasoner"),
        name: Cow::Borrowed("DeepSeek Reasoner"),
        family: Some(Cow::Borrowed("deepseek-thinking")),
        reasoning_efforts: Cow::Borrowed(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: None,
        temperature: Some(true),
        knowledge: Some(Cow::Borrowed("2025-09")),
        release_date: Some(Cow::Borrowed("2025-12-01")),
        last_updated: Some(Cow::Borrowed("2026-02-28")),
        open_weights: Some(true),
        input_modalities: Cow::Borrowed(&["text"]),
        output_modalities: Cow::Borrowed(&["text"]),
        cost: Some(ModelCost { input: 0.28, output: 0.42, reasoning: None, cache_read: Some(0.028), cache_write: None, input_audio: None, output_audio: None }),
        limit: Some(ModelLimit { context: 128000, input: None, output: 64000 }),
        status: None,
        capabilities: None,
    },
];

pub const PRESET: OpenAiConfigPreset = OpenAiConfigPreset {
    name: "deepseek",
    base_url: "https://api.deepseek.com",
    default_model: "deepseek-chat",
    env_key: "DEEPSEEK_API_KEY",
    models: MODELS,
    supported_api_surfaces: &[OpenAiApiSurface::ChatCompletions],
};
