[package]
name = "provider-anthropic"
edition.workspace = true
version.workspace = true

[dependencies]
async-stream = { workspace = true }
eventsource-stream = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
dotenvy = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
