[package]
name = "chat"
edition.workspace = true
version.workspace = true

[dependencies]
chrono = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
