[package]
name = "agent-acp"
edition.workspace = true
version.workspace = true

[dependencies]
agent-client-protocol = { workspace = true }
agent-core = { workspace = true }
agent-runtime = { workspace = true }
agent-store = { workspace = true }
async-trait = "0.1"
futures = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["io-std", "sync"] }
tokio-util = { workspace = true, features = ["compat"] }
tracing = { workspace = true }
ulid = { workspace = true }
provider = { workspace = true }
