[package]
name = "brain-loops"
edition.workspace = true
version.workspace = true

[dependencies]
brain-types = { workspace = true }
futures = { workspace = true }
ulid = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
tokio-util = { workspace = true }
tokio-stream = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
async-stream = { workspace = true }
