use brain_types::{ModelCost, ModelInfo, ModelLimit};

use super::config::OpenAiConfig;

const REASONING_LMH: &[&str] = &["low", "medium", "high"];

const OPENAI_MODELS: &[ModelInfo] = &[
    ModelInfo {
        id: "gpt-4o",
        name: "GPT-4o",
        family: Some("gpt"),
        reasoning: None,
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(true),
        knowledge: Some("2023-09"),
        release_date: Some("2024-05-13"),
        last_updated: Some("2024-08-06"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 2.5,
            output: 10.0,
            reasoning: None,
            cache_read: Some(1.25),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 128_000,
            input: None,
            output: 16_384,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-4o-mini",
        name: "GPT-4o mini",
        family: Some("gpt-mini"),
        reasoning: None,
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(true),
        knowledge: Some("2023-09"),
        release_date: Some("2024-07-18"),
        last_updated: Some("2024-07-18"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 0.15,
            output: 0.6,
            reasoning: None,
            cache_read: Some(0.08),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 128_000,
            input: None,
            output: 16_384,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-4.1",
        name: "GPT-4.1",
        family: Some("gpt"),
        reasoning: None,
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(true),
        knowledge: Some("2024-04"),
        release_date: Some("2025-04-14"),
        last_updated: Some("2025-04-14"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 2.0,
            output: 8.0,
            reasoning: None,
            cache_read: Some(0.5),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 1_047_576,
            input: None,
            output: 32_768,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-4.1-mini",
        name: "GPT-4.1 mini",
        family: Some("gpt-mini"),
        reasoning: None,
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(true),
        knowledge: Some("2024-04"),
        release_date: Some("2025-04-14"),
        last_updated: Some("2025-04-14"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 0.4,
            output: 1.6,
            reasoning: None,
            cache_read: Some(0.1),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 1_047_576,
            input: None,
            output: 32_768,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-4.1-nano",
        name: "GPT-4.1 nano",
        family: Some("gpt-nano"),
        reasoning: None,
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(true),
        knowledge: Some("2024-04"),
        release_date: Some("2025-04-14"),
        last_updated: Some("2025-04-14"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 0.1,
            output: 0.4,
            reasoning: None,
            cache_read: Some(0.03),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 1_047_576,
            input: None,
            output: 32_768,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-5",
        name: "GPT-5",
        family: Some("gpt"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-09-30"),
        release_date: Some("2025-08-07"),
        last_updated: Some("2025-08-07"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.25,
            output: 10.0,
            reasoning: None,
            cache_read: Some(0.125),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 400_000,
            input: Some(272_000),
            output: 128_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-5-mini",
        name: "GPT-5 Mini",
        family: Some("gpt-mini"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-05-30"),
        release_date: Some("2025-08-07"),
        last_updated: Some("2025-08-07"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 0.25,
            output: 2.0,
            reasoning: None,
            cache_read: Some(0.025),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 400_000,
            input: Some(272_000),
            output: 128_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-5-nano",
        name: "GPT-5 Nano",
        family: Some("gpt-nano"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-05-30"),
        release_date: Some("2025-08-07"),
        last_updated: Some("2025-08-07"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 0.05,
            output: 0.4,
            reasoning: None,
            cache_read: Some(0.005),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 400_000,
            input: Some(272_000),
            output: 128_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "o3",
        name: "o3",
        family: Some("o"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-05"),
        release_date: Some("2025-04-16"),
        last_updated: Some("2025-04-16"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 2.0,
            output: 8.0,
            reasoning: None,
            cache_read: Some(0.5),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 200_000,
            input: None,
            output: 100_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "o3-mini",
        name: "o3-mini",
        family: Some("o-mini"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: false,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-05"),
        release_date: Some("2024-12-20"),
        last_updated: Some("2025-01-29"),
        open_weights: Some(false),
        input_modalities: &["text"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.1,
            output: 4.4,
            reasoning: None,
            cache_read: Some(0.55),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 200_000,
            input: None,
            output: 100_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "o3-pro",
        name: "o3-pro",
        family: Some("o-pro"),
        reasoning: Some(&["high"]),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-05"),
        release_date: Some("2025-06-10"),
        last_updated: Some("2025-06-10"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 20.0,
            output: 80.0,
            reasoning: None,
            cache_read: None,
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 200_000,
            input: None,
            output: 100_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "o4-mini",
        name: "o4-mini",
        family: Some("o-mini"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-05"),
        release_date: Some("2025-04-16"),
        last_updated: Some("2025-04-16"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.1,
            output: 4.4,
            reasoning: None,
            cache_read: Some(0.28),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 200_000,
            input: None,
            output: 100_000,
        }),
        status: None,
    },
];

#[derive(Debug, Clone, Copy)]
pub struct OpenAiConfigPreset {
    pub name: &'static str,
    pub base_url: &'static str,
    pub default_model: &'static str,
    pub env_key: &'static str,
    pub models: &'static [ModelInfo],
}

impl OpenAiConfigPreset {
    pub const OPENAI: Self = Self {
        name: "openai",
        base_url: "https://api.openai.com/v1",
        default_model: "gpt-4o-mini",
        env_key: "OPENAI_API_KEY",
        models: OPENAI_MODELS,
    };
    pub const GROQ: Self = Self {
        name: "groq",
        base_url: "https://api.groq.com/openai/v1",
        default_model: "llama-3.3-70b-versatile",
        env_key: "GROQ_API_KEY",
        models: &[],
    };
    pub const DEEPSEEK: Self = Self {
        name: "deepseek",
        base_url: "https://api.deepseek.com",
        default_model: "deepseek-chat",
        env_key: "DEEPSEEK_API_KEY",
        models: &[],
    };
    pub const TOGETHER: Self = Self {
        name: "together",
        base_url: "https://api.together.xyz/v1",
        default_model: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        env_key: "TOGETHER_API_KEY",
        models: &[],
    };
    pub const XAI: Self = Self {
        name: "xai",
        base_url: "https://api.x.ai/v1",
        default_model: "grok-3-mini",
        env_key: "XAI_API_KEY",
        models: &[],
    };
    pub const FIREWORKS: Self = Self {
        name: "fireworks",
        base_url: "https://api.fireworks.ai/inference/v1",
        default_model: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        env_key: "FIREWORKS_API_KEY",
        models: &[],
    };
    pub const MISTRAL: Self = Self {
        name: "mistral",
        base_url: "https://api.mistral.ai/v1",
        default_model: "mistral-large-latest",
        env_key: "MISTRAL_API_KEY",
        models: &[],
    };
    pub const OPENROUTER: Self = Self {
        name: "openrouter",
        base_url: "https://openrouter.ai/api/v1",
        default_model: "openai/gpt-4o-mini",
        env_key: "OPENROUTER_API_KEY",
        models: &[],
    };
    pub const OLLAMA: Self = Self {
        name: "ollama",
        base_url: "http://localhost:11434/v1",
        default_model: "llama3.3",
        env_key: "OLLAMA_API_KEY",
        models: &[],
    };
    pub const GEMINI: Self = Self {
        name: "gemini",
        base_url: "https://generativelanguage.googleapis.com/v1beta/openai",
        default_model: "gemini-2.0-flash",
        env_key: "GEMINI_API_KEY",
        models: &[],
    };
    pub const MINIMAX: Self = Self {
        name: "minimax",
        base_url: "https://api.minimax.chat/v1",
        default_model: "MiniMax-Text-01",
        env_key: "MINIMAX_API_KEY",
        models: &[],
    };

    pub const ALL: &[Self] = &[
        Self::OPENAI,
        Self::GROQ,
        Self::DEEPSEEK,
        Self::TOGETHER,
        Self::XAI,
        Self::FIREWORKS,
        Self::MISTRAL,
        Self::OPENROUTER,
        Self::OLLAMA,
        Self::GEMINI,
        Self::MINIMAX,
    ];

    pub fn by_name(name: &str) -> Option<Self> {
        let lower = name.to_ascii_lowercase();
        Self::ALL.iter().find(|p| p.name == lower).copied()
    }

    pub fn into_config(self, api_key: impl Into<String>) -> OpenAiConfig {
        OpenAiConfig {
            name: self.name.to_owned(),
            api_key: api_key.into(),
            base_url: self.base_url.to_owned(),
            default_model: self.default_model.to_owned(),
            models: self.models,
        }
    }

    /// Try to load the API key from the environment and build a config.
    /// Returns `None` if the env var is not set.
    pub fn from_env(self) -> Option<OpenAiConfig> {
        std::env::var(self.env_key)
            .ok()
            .map(|key| self.into_config(key))
    }
}
