// This file is generated by `provider-preset-gen`. Do not edit manually.
use brain_types::ModelInfo;

use super::{OpenAiConfigPreset, REASONING_LMH};
use crate::openai::config::OpenAiApiSurface;

pub const MODELS: &[ModelInfo] = &[
    ModelInfo {
        id: "deepseek-chat",
        name: "DeepSeek Chat",
        family: Some("deepseek"),
        reasoning: None,
        tool_call: true,
        attachment: true,
        structured_output: None,
        temperature: Some(true),
        knowledge: Some("2025-09"),
        release_date: Some("2025-12-01"),
        last_updated: Some("2026-02-28"),
        open_weights: Some(true),
        input_modalities: &["text"],
        output_modalities: &["text"],
        cost: Some(brain_types::ModelCost {
            input: 0.28,
            output: 0.42,
            reasoning: None,
            cache_read: Some(0.028),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(brain_types::ModelLimit {
            context: 128000,
            input: None,
            output: 8192,
        }),
        status: None,
    },
    ModelInfo {
        id: "deepseek-reasoner",
        name: "DeepSeek Reasoner",
        family: Some("deepseek-thinking"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: None,
        temperature: Some(true),
        knowledge: Some("2025-09"),
        release_date: Some("2025-12-01"),
        last_updated: Some("2026-02-28"),
        open_weights: Some(true),
        input_modalities: &["text"],
        output_modalities: &["text"],
        cost: Some(brain_types::ModelCost {
            input: 0.28,
            output: 0.42,
            reasoning: None,
            cache_read: Some(0.028),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(brain_types::ModelLimit {
            context: 128000,
            input: None,
            output: 64000,
        }),
        status: None,
    },
];

pub const PRESET: OpenAiConfigPreset = OpenAiConfigPreset {
    name: "deepseek",
    base_url: "https://api.deepseek.com",
    default_model: "deepseek-chat",
    env_key: "DEEPSEEK_API_KEY",
    models: MODELS,
    supported_api_surfaces: &[OpenAiApiSurface::ChatCompletions],
};
