// This file is generated by `provider-preset-gen`. Do not edit manually.
pub mod deepseek;
pub mod fireworks;
pub mod gemini;
pub mod groq;
pub mod minimax;
pub mod mistral;
pub mod ollama;
pub mod openai;
pub mod openrouter;
pub mod together;
pub mod xai;

use brain_types::ModelInfo;

use super::config::OpenAiConfig;

const REASONING_LMH: &[&str] = &["low", "medium", "high"];

#[derive(Debug, Clone, Copy)]
pub struct OpenAiConfigPreset {
    pub name: &'static str,
    pub base_url: &'static str,
    pub default_model: &'static str,
    pub env_key: &'static str,
    pub models: &'static [ModelInfo],
}

impl OpenAiConfigPreset {
    pub const OPENAI: Self = openai::PRESET;
    pub const GROQ: Self = groq::PRESET;
    pub const DEEPSEEK: Self = deepseek::PRESET;
    pub const TOGETHER: Self = together::PRESET;
    pub const XAI: Self = xai::PRESET;
    pub const FIREWORKS: Self = fireworks::PRESET;
    pub const MISTRAL: Self = mistral::PRESET;
    pub const OPENROUTER: Self = openrouter::PRESET;
    pub const OLLAMA: Self = ollama::PRESET;
    pub const GEMINI: Self = gemini::PRESET;
    pub const MINIMAX: Self = minimax::PRESET;

    pub const ALL: &[Self] = &[
        Self::OPENAI,
        Self::GROQ,
        Self::DEEPSEEK,
        Self::TOGETHER,
        Self::XAI,
        Self::FIREWORKS,
        Self::MISTRAL,
        Self::OPENROUTER,
        Self::OLLAMA,
        Self::GEMINI,
        Self::MINIMAX,
    ];

    pub fn by_name(name: &str) -> Option<Self> {
        let lower = name.to_ascii_lowercase();
        Self::ALL
            .iter()
            .find(|preset| preset.name == lower)
            .copied()
    }

    pub fn into_config(self, api_key: impl Into<String>) -> OpenAiConfig {
        OpenAiConfig {
            name: self.name.to_owned(),
            api_key: api_key.into(),
            base_url: self.base_url.to_owned(),
            default_model: self.default_model.to_owned(),
            models: self.models,
        }
    }

    pub fn from_env(self) -> Option<OpenAiConfig> {
        std::env::var(self.env_key)
            .ok()
            .map(|key| self.into_config(key))
    }
}
