use brain_types::{ModelCost, ModelInfo, ModelLimit};

const REASONING_LMH: &[&str] = &["low", "medium", "high"];

const CODEX_MODELS: &[ModelInfo] = &[
    ModelInfo {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        family: Some("gpt-codex"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2025-08-31"),
        release_date: Some("2026-02-05"),
        last_updated: Some("2026-02-05"),
        open_weights: Some(false),
        input_modalities: &["text", "image", "pdf"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.75,
            output: 14.0,
            reasoning: None,
            cache_read: Some(0.175),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 400_000,
            input: Some(272_000),
            output: 128_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-5.3-codex-spark",
        name: "GPT-5.3 Codex Spark",
        family: Some("gpt-codex-spark"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2025-08-31"),
        release_date: Some("2026-02-05"),
        last_updated: Some("2026-02-05"),
        open_weights: Some(false),
        input_modalities: &["text", "image", "pdf"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.75,
            output: 14.0,
            reasoning: None,
            cache_read: Some(0.175),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 128_000,
            input: Some(100_000),
            output: 32_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-5.2-codex",
        name: "GPT-5.2 Codex",
        family: Some("gpt-codex"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2025-08-31"),
        release_date: Some("2025-12-11"),
        last_updated: Some("2025-12-11"),
        open_weights: Some(false),
        input_modalities: &["text", "image", "pdf"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.75,
            output: 14.0,
            reasoning: None,
            cache_read: Some(0.175),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 400_000,
            input: Some(272_000),
            output: 128_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-5.1-codex",
        name: "GPT-5.1 Codex",
        family: Some("gpt-codex"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-09-30"),
        release_date: Some("2025-11-13"),
        last_updated: Some("2025-11-13"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.25,
            output: 10.0,
            reasoning: None,
            cache_read: Some(0.125),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 400_000,
            input: Some(272_000),
            output: 128_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-5.1-codex-max",
        name: "GPT-5.1 Codex Max",
        family: Some("gpt-codex"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-09-30"),
        release_date: Some("2025-11-13"),
        last_updated: Some("2025-11-13"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.25,
            output: 10.0,
            reasoning: None,
            cache_read: Some(0.125),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 400_000,
            input: Some(272_000),
            output: 128_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-5.1-codex-mini",
        name: "GPT-5.1 Codex mini",
        family: Some("gpt-codex"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-09-30"),
        release_date: Some("2025-11-13"),
        last_updated: Some("2025-11-13"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 0.25,
            output: 2.0,
            reasoning: None,
            cache_read: Some(0.025),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 400_000,
            input: Some(272_000),
            output: 128_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "gpt-5-codex",
        name: "GPT-5-Codex",
        family: Some("gpt-codex"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: false,
        structured_output: Some(true),
        temperature: Some(false),
        knowledge: Some("2024-09-30"),
        release_date: Some("2025-09-15"),
        last_updated: Some("2025-09-15"),
        open_weights: Some(false),
        input_modalities: &["text", "image"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.25,
            output: 10.0,
            reasoning: None,
            cache_read: Some(0.125),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 400_000,
            input: Some(272_000),
            output: 128_000,
        }),
        status: None,
    },
    ModelInfo {
        id: "codex-mini-latest",
        name: "Codex Mini",
        family: Some("gpt-codex-mini"),
        reasoning: Some(REASONING_LMH),
        tool_call: true,
        attachment: true,
        structured_output: None,
        temperature: Some(false),
        knowledge: Some("2024-04"),
        release_date: Some("2025-05-16"),
        last_updated: Some("2025-05-16"),
        open_weights: Some(false),
        input_modalities: &["text"],
        output_modalities: &["text"],
        cost: Some(ModelCost {
            input: 1.5,
            output: 6.0,
            reasoning: None,
            cache_read: Some(0.375),
            cache_write: None,
            input_audio: None,
            output_audio: None,
        }),
        limit: Some(ModelLimit {
            context: 200_000,
            input: None,
            output: 100_000,
        }),
        status: None,
    },
];

/// Preset containing all OAuth endpoint URLs, client ID, and scopes
/// for an OpenAI OAuth provider.
#[derive(Debug, Clone, Copy)]
pub struct OpenAiOAuthPreset {
    pub name: &'static str,
    pub issuer: &'static str,
    pub authorize_url: &'static str,
    pub token_url: &'static str,
    pub device_code_url: &'static str,
    pub device_token_url: &'static str,
    pub device_verification_url: &'static str,
    pub device_redirect_uri: &'static str,
    pub client_id: &'static str,
    pub scopes: &'static str,
    pub api_base_url: &'static str,
    pub default_model: &'static str,
    pub callback_port: u16,
    pub models: &'static [ModelInfo],
}

impl OpenAiOAuthPreset {
    pub const OPENAI: Self = Self {
        name: "openai-oauth",
        issuer: "https://auth.openai.com",
        authorize_url: "https://auth.openai.com/oauth/authorize",
        token_url: "https://auth.openai.com/oauth/token",
        device_code_url: "https://auth.openai.com/api/accounts/deviceauth/usercode",
        device_token_url: "https://auth.openai.com/api/accounts/deviceauth/token",
        device_verification_url: "https://auth.openai.com/codex/device",
        device_redirect_uri: "https://auth.openai.com/deviceauth/callback",
        client_id: "app_EMoamEEZ73f0CkXaXp7hrann",
        scopes: "openid profile email offline_access",
        api_base_url: "https://chatgpt.com/backend-api/codex",
        default_model: "gpt-5.3-codex",
        callback_port: 1455,
        models: CODEX_MODELS,
    };
}
