[package]
name = "chat-teams"
edition.workspace = true
version.workspace = true

[dependencies]
chat = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tokio-stream = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
