//! Shared token-usage metadata for provider responses.

use serde::{Deserialize, Serialize};

/// Aggregate token accounting for a completed or in-progress response.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Usage {
    /// Tokens consumed from the prompt or transcript.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<u32>,
    /// Tokens generated by the model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<u32>,
    /// Total tokens when the upstream provider reports it explicitly.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_tokens: Option<u32>,
    /// Tokens read from a prompt or response cache.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_read_tokens: Option<u32>,
    /// Tokens written into a prompt or response cache.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_write_tokens: Option<u32>,
    /// Tokens attributed to reasoning or thinking output.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<u32>,
}

impl Usage {
    /// Builds a [`Usage`] value and derives `total_tokens` when both sides are
    /// available.
    pub fn with_totals(input_tokens: Option<u32>, output_tokens: Option<u32>) -> Self {
        let total_tokens = match (input_tokens, output_tokens) {
            (Some(input), Some(output)) => Some(input.saturating_add(output)),
            _ => None,
        };

        Self {
            input_tokens,
            output_tokens,
            total_tokens,
            ..Self::default()
        }
    }
}
