[package]
name = "agent-loops"
edition.workspace = true
version.workspace = true

[dependencies]
agent-runtime = { path = "../agent-runtime" }
futures = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
provider = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
ulid = { workspace = true }
async-stream = { workspace = true }
